#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=10000
SAVEHIST=10000

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/opt/python@3.10/bin/:$PATH"
export PATH="/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/:$PATH"
export PATH="/Users/teddyobrien/Library/Python/3.10/lib/python/site-packages:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.spicetify:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export JAVA_HOME=/opt/homebrew/opt/java/

export GOPATH="$HOME/Go"
# export TERM="xterm-kitty"
export BAT_THEME="Dracula"
