#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=10000
SAVEHIST=10000

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export PATH="$HOME/bin:$PATH"

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export QT_QPA_PLATFORMTHEME="qt6ct"
