#! /bin/sh

# Start new sxhkd session
pgrep -x sxhkd > /dev/null || sxhkd &
# Autostart (XDG)
dex -a

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop="^1"

polybar top-bar &
nitrogen --restore 
nm-applet &
